apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
type: Opaque
data:
  # This is example-key:
  #   $ echo -n "my-super-secret-key" | base64
  #   bXktc3VwZXItc2VjcmV0LWtleQ==
  exact-time-secret-key: bXktc3VwZXItc2VjcmV0LWtleQ==